import { z } from 'zod';

const portfolioImageSchema = z.object({
  src: z.string().startsWith('/work/'),
  alt: z.string().min(12),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
});

const projectSchema = z.object({
  index: z.string().regex(/^0[1-9]$/),
  slug: z.string().regex(/^[a-z0-9-]+$/),
  title: z.string().min(2),
  category: z.string().min(4),
  year: z.number().int().min(2024),
  role: z.string().min(5),
  scope: z.array(z.string()).min(3),
  summary: z.string().min(40),
  context: z.string().min(80),
  problem: z.string().min(80),
  audience: z.string().min(40),
  goals: z.array(z.string()).min(3),
  ia: z.array(z.string()).min(4),
  flow: z.string().min(40),
  ux: z.array(z.string()).min(3),
  artDirection: z.string().min(60),
  typography: z.string().min(30),
  colors: z.array(z.string()).min(3),
  responsive: z.string().min(50),
  implementation: z.string().min(60),
  accessibility: z.array(z.string()).min(3),
  testing: z.array(z.string()).min(3),
  limitations: z.array(z.string()).min(2),
  liveUrl: z.string().url(),
  githubUrl: z.string().url(),
  figmaUrl: z.string().url().nullable(),
  cover: portfolioImageSchema,
  mobile: portfolioImageSchema,
  gallery: z.array(portfolioImageSchema).min(3),
});

export type Project = z.infer<typeof projectSchema>;

const projectData: Project[] = [
  {
    index: '01',
    slug: 'techdelo-40',
    title: 'ТЕХДЕЛО 40',
    category: 'Аренда спецтехники · B2B',
    year: 2026,
    role: 'Исследование · UX/UI · Frontend',
    scope: ['research', 'catalog UX', 'design system', 'Next.js', 'QA'],
    summary: 'Сайт регионального сервиса аренды: каталог из 12 машин, подбор от задачи, detail pages и структурированная заявка.',
    context: 'Региональным заказчикам важно ещё до звонка понять, какая техника подходит, во что входит смена и от чего зависит подача. Проект собран как цельный B2B-продукт для Калуги и выездов по ЦФО.',
    problem: 'Большинство сайтов ниши смешивает SEO-текст, цены и повторяющиеся формы. Пользователь вынужден звонить до того, как сравнил модели, минимальный заказ и ограничения площадки.',
    audience: 'Прорабы, снабженцы, владельцы небольших производств и частные заказчики, которым нужно быстро подобрать машину под конкретную работу.',
    goals: ['Дать два понятных входа: по модели и по задаче.', 'Показать условия аренды до формы.', 'Собирать предметный контекст без обещания точной цены до осмотра.'],
    ia: ['Главная', 'Каталог и фильтры', 'Карточка техники', 'Подбор по задаче', 'Заявка в три шага'],
    flow: 'Главная → задача или каталог → подходящая техника → параметры и условия → проверка заявки.',
    ux: ['Фильтры по типу, задаче, цене и минимальному заказу.', 'Отдельный task-based сценарий для тех, кто не знает модель.', 'Sticky CTA и mobile filter sheet без зависимости от hover.'],
    artDirection: 'Сдержанная промышленная система: тёплый бумажный фон, почти чёрные панели, кислотно-лаймовый сигнал и крупная типографика. Акцент сообщает действие, а не декорирует каждый блок.',
    typography: 'Manrope Variable для интерфейса и плотных коммерческих заголовков.',
    colors: ['Ink #121713', 'Paper #F2F0E8', 'Signal #CFFF2E'],
    responsive: 'Каталог, фильтры и длинные характеристики перестраиваются на 360/390 px; mobile CTA закреплён у safe area, горизонтальный overflow исключён.',
    implementation: 'Next.js 16, React 19, TypeScript strict, Tailwind CSS 4 и Zod. Контент, фильтры, расчёт условий и форма покрыты самостоятельной бизнес-логикой.',
    accessibility: ['Семантические страницы и последовательные заголовки.', 'Видимый focus, touch targets и keyboard navigation.', 'Axe WCAG A/AA: 0 блокирующих нарушений.'],
    testing: ['6/6 unit-тестов.', 'Production build: 26 маршрутов.', 'Lighthouse desktop 100/100/100/100; mobile 84/100/100/100.'],
    limitations: ['Backend и настоящая отправка заявок намеренно не подключены.', 'Figma-файл упомянут в исходном проекте, но подтверждённой публичной ссылки нет.'],
    liveUrl: 'https://techdelo-40-demo.vercel.app',
    githubUrl: 'https://github.com/quenyu/techdelo-40-demo',
    figmaUrl: null,
    cover: { src: '/work/techdelo-40/cover.webp', alt: 'Главная страница сайта аренды спецтехники ТЕХДЕЛО 40 на desktop', width: 1200, height: 834 },
    mobile: { src: '/work/techdelo-40/mobile.webp', alt: 'Мобильный первый экран сайта ТЕХДЕЛО 40', width: 390, height: 844 },
    gallery: [
      { src: '/work/techdelo-40/catalog.webp', alt: 'Каталог спецтехники с фильтрами и карточками машин', width: 1200, height: 1050 },
      { src: '/work/techdelo-40/equipment.webp', alt: 'Подробная страница единицы спецтехники с условиями аренды', width: 1200, height: 1050 },
      { src: '/work/techdelo-40/catalog-mobile.webp', alt: 'Мобильный каталог спецтехники с доступной навигацией', width: 390, height: 920 },
      { src: '/work/techdelo-40/form-success.webp', alt: 'Локальный итог успешно проверенной заявки на мобильном', width: 390, height: 920 },
    ],
  },
  {
    index: '02',
    slug: 'poluton',
    title: 'ПОЛУТОН',
    category: 'Specialty coffee · Lifestyle',
    year: 2026,
    role: 'Brand direction · UX/UI · 3D · Frontend',
    scope: ['brand system', 'editorial UI', 'motion', 'WebGL', 'preorder UX'],
    summary: 'Выразительный сайт specialty coffee с брендингом, интерактивным 3D-объектом, меню, визитом и заказом к выдаче.',
    context: 'Локальной кофейне нужно одновременно создать эмоциональное впечатление и за несколько секунд ответить на практические вопросы: что заказать, сколько это стоит и когда забрать.',
    problem: 'Hospitality-сайты часто выбирают только одну сторону: характер без удобного меню или утилитарность без собственной визуальной позиции. Здесь оба слоя собраны в один короткий путь.',
    audience: 'Горожане, которые выбирают место по атмосфере, но ожидают быстрый mobile-доступ к меню, часам работы, маршруту и предзаказу.',
    goals: ['Сформировать собственный бренд-язык без кофейного бежевого клише.', 'Сделать меню и предзаказ самостоятельными сценариями.', 'Сохранить выразительный motion без блокировки HTML и mobile.'],
    ia: ['Главная', 'Меню', 'Корзина', 'Предзаказ', 'Визит'],
    flow: 'Home / Menu → категория → напиток и состав → корзина → слот выдачи → локальная проверка.',
    ux: ['Категории, объёмы, составы и dietary tags доступны без 3D.', 'Visit собирает адрес, часы, статус и маршрут без тяжёлой карты.', 'Static fallback включается на mobile, reduced motion и слабых устройствах.'],
    artDirection: 'Идея строится на полутоне между кислым и горьким: Oyster paper, Cobalt и Persimmon, разрез как brand device и намеренно несбалансированная editorial-композиция.',
    typography: 'Unbounded для смысловых акцентов, Manrope для интерфейса и длинного русского текста.',
    colors: ['Oyster #F3F0E8', 'Cobalt #3B4BFF', 'Persimmon #FF6248'],
    responsive: 'WebGL запускается только на подходящем desktop, а 44 KB fallback сохраняет композицию на 360–768 px. Все продуктовые маршруты проверены без overflow.',
    implementation: 'Next.js, React, TypeScript, Motion и React Three Fiber. 3D-стакан процедурный, грузится после usable HTML и не участвует в критическом UX.',
    accessibility: ['HTML остаётся полноценным без canvas.', 'Keyboard/focus, reduced motion и static fallback.', 'Axe: 0 serious/critical на ключевых маршрутах desktop и mobile.'],
    testing: ['4/4 unit-теста.', '10 статических production-маршрутов.', 'FCP 148–184 ms, CLS 0.0012/0.0007 в сохранённом local production audit.'],
    limitations: ['Предзаказ валидируется локально и не отправляется в реальную кассу.', 'Созданный Figma-файл не заявляется как полностью заполненный UI kit.'],
    liveUrl: 'https://poluton-coffee-demo.vercel.app',
    githubUrl: 'https://github.com/quenyu/poluton-coffee-demo',
    figmaUrl: 'https://www.figma.com/design/0MmlhT2IiB8oBj5UvvjBkJ',
    cover: { src: '/work/poluton/cover.webp', alt: 'Первый экран сайта specialty coffee ПОЛУТОН на desktop', width: 1200, height: 834 },
    mobile: { src: '/work/poluton/mobile.webp', alt: 'Мобильный первый экран сайта ПОЛУТОН', width: 390, height: 844 },
    gallery: [
      { src: '/work/poluton/hero-3d.webp', alt: 'Интерактивный двухцветный 3D-стакан в hero', width: 1200, height: 742 },
      { src: '/work/poluton/menu.webp', alt: 'Меню кофейни с категориями напитков и ценами', width: 1200, height: 792 },
      { src: '/work/poluton/preorder.webp', alt: 'Сценарий предзаказа кофе к выбранному времени', width: 1200, height: 834 },
      { src: '/work/poluton/location.webp', alt: 'Секция визита с адресом и часами работы кофейни', width: 1200, height: 671 },
    ],
  },
  {
    index: '03',
    slug: 'gran-auto',
    title: 'ГРАНЬ АВТО',
    category: 'Кузовной центр · Local service',
    year: 2026,
    role: 'Research · Conversion UX · Frontend',
    scope: ['service catalog', 'before/after', 'estimate flow', 'accessibility', 'E2E'],
    summary: 'Сайт кузовного центра: услуги, сценарии ремонта, сравнение до/после и пятишаговая предварительная оценка по фото.',
    context: 'Владельцу автомобиля нужно понять вероятный путь ремонта до передачи контакта, а сервису — получить повреждение, деталь, автомобиль и полезные ракурсы без ложной фиксированной цены.',
    problem: 'Локальные сайты перечисляют услуги, но редко связывают видимое повреждение с процессом и сравнимой работой. Переход сразу в мессенджер оставляет заявку неструктурированной.',
    audience: 'Автовладельцы из Калуги, которым важны прозрачность оценки, согласование скрытых работ, совпадение оттенка и реалистичный диапазон сроков.',
    goals: ['Связать повреждение, услугу и релевантный сценарий.', 'Объяснить, почему оценка по фото предварительная.', 'Собрать полезные ракурсы и контакт в контролируемом flow.'],
    ia: ['Главная', 'Каталог услуг', 'Сценарии ремонта', 'Оценка по фото', 'Контакты'],
    flow: 'Повреждение → услуга → похожая работа → пять шагов оценки → review → server validation без хранения.',
    ux: ['Фильтры по услуге и повреждению.', 'Keyboard/touch before-after comparator.', 'Подсказки по общему, крупному и угловому ракурсу прямо в загрузке.'],
    artDirection: 'Образ контролируемой кузовной лаборатории: молочная поверхность, графитовые панели и один оранжево-красный сигнал. Линия контроля связывает hero, кейсы, форму и focus states.',
    typography: 'Системный гротеск с плотной editorial-иерархией и техническими подписями.',
    colors: ['Milk #F3F0E9', 'Graphite #17191B', 'Signal #F04420'],
    responsive: 'Все ключевые маршруты проверены на 360/768/1440 px. Touch targets не меньше 44 px, mobile CTA учитывает safe area, overflow отсутствует.',
    implementation: 'Next.js App Router, React 19, TypeScript strict, Zod и multipart validation. Контент услуг и сценариев типизирован; endpoint проверяет payload и файлы, но ничего не сохраняет.',
    accessibility: ['Нативные form controls и семантические landmarks.', 'Ошибки с role=alert, доступный progress и фильтры.', 'Lighthouse Accessibility 100 на проверенных страницах.'],
    testing: ['7/7 unit/component тестов.', '42 E2E-теста на desktop/tablet/mobile.', 'Lighthouse: home 94/100/100/100; work 99/100/100/100.'],
    limitations: ['Нет хранения, CRM, email или аналитики.', 'Figma-файл создан, но заполнение было остановлено лимитом Starter-плана.'],
    liveUrl: 'https://gran-auto.vercel.app',
    githubUrl: 'https://github.com/quenyu/gran-auto',
    figmaUrl: 'https://www.figma.com/design/bRL1jo6aO8bANEwoH98nrP',
    cover: { src: '/work/gran-auto/cover.webp', alt: 'Главная страница кузовного центра ГРАНЬ АВТО на desktop', width: 1200, height: 834 },
    mobile: { src: '/work/gran-auto/mobile.webp', alt: 'Мобильный первый экран сайта ГРАНЬ АВТО', width: 360, height: 844 },
    gallery: [
      { src: '/work/gran-auto/service.webp', alt: 'Подробная страница услуги кузовного ремонта', width: 1200, height: 1050 },
      { src: '/work/gran-auto/work.webp', alt: 'Страница сценария ремонта с операциями и результатом', width: 1200, height: 1050 },
      { src: '/work/gran-auto/comparison.webp', alt: 'Интерактивное сравнение состояния детали до и после', width: 1200, height: 876 },
      { src: '/work/gran-auto/estimate.webp', alt: 'Многошаговый сценарий предварительной оценки по фото', width: 1200, height: 1050 },
    ],
  },
];

export const projects = z.array(projectSchema).length(3).parse(projectData);

const profileSchema = z.object({
  name: z.string(),
  location: z.string(),
  role: z.string(),
  github: z.string().url(),
  telegram: z.string().url(),
  email: z.string().email().nullable(),
});

export const profile = profileSchema.parse({
  name: 'Артём Исаев',
  location: 'Калуга',
  role: 'Web designer + frontend developer',
  github: 'https://github.com/quenyu',
  telegram: 'https://t.me/wqeqadas',
  email: null,
});

export const services = [
  ['01', 'Лендинг / корпоративный сайт', 'Исследование, структура, дизайн в Figma и цельный интерфейс для услуги или компании.'],
  ['02', 'Редизайн и UX-структура', 'Аудит текущего сайта, новая архитектура и аккуратный перенос полезного контента.'],
  ['03', 'Frontend-реализация', 'Типизированная разработка интерфейса, состояний и содержательных маршрутов.'],
  ['04', 'Адаптив и запуск', 'Проверка ключевых ширин, доступности, production build и развёртывание.'],
] as const;

export const process = [
  ['01', 'research', 'Бизнес, аудитория, контекст и ограничения.'],
  ['02', 'structure', 'Информационная архитектура и пользовательский путь.'],
  ['03', 'design', 'Прототип, визуальная система и ключевые состояния.'],
  ['04', 'build + launch', 'Responsive frontend, проверка и production.'],
] as const;

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
